Ceci a été écrit de la branche master
jobs:
    - job: MyTestPipeline
      pool:
        vmImage: 'ubuntu-latest'
      steps:
        - script: echo hello from Linux
        - task: DownloadGitHubRelease@0
          inputs:
            connection: 'EmmanuelVergnaud'
            userRepository: 'MonRepoPublic'
            defaultVersionType: 'latest'
            downloadPath: '$(System.ArtifactsDirectory)'
        - task: ArchiveFiles@2
          inputs:
            rootFolderOrFile: '$(Build.BinariesDirectory)'
            includeRootFolder: true
            archiveType: 'zip'
            archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
            replaceExistingArchive: true
        - task: PowerShell@2
          inputs:
            targetType: 'inline'
            script: |
              # Write your PowerShell commands here.
              
              Write-Host "Hello World"
            errorActionPreference: 'continue'


